### PR TITLE
Text overhaul to make it read nice.

### PR DESCRIPTION
**Pull request by jackVanish**
Went over this one to clean up the text and make it read a little more smoothly, would appreciate a second (and third) set of eyes. A few questions I think @CaitlinBate and @SoftwareMonk are better able to answer than I, but which should be addressed either in this merge or separate tickets of their own, depending on scope: 

- We have 'glatos' in backticks to make it look like cool code and help distinguish it from GLATOS. Should we also do that for VTrack, since it's a package name? Or do we want to leave it as plain text? 
- The code has a brief digression into using the custom 'normDate' function to normalize some wrongly formatted dates in the dataset. If I'm remembering right, though, normDate was a kludge that I desperately hacked into the lesson at the last minute to make the provided dataset work. It works, sure, and I'm not AGAINST leaving it in, but it's a little bit left-field. We're making all this hullaballoo about how powerful glatos is and then suddenly sidestep for a second to write a custom, bolted-on function so that glatos doesn't choke on the dataset WE decided to use for the workshop? Seems like not a great look. The way I see it, we have a few options: 
1. We leave it in and write some exposition around it to say, basically, 'this is an object lesson in how not every package can do everything and you need to cultivate an awareness of what you're running, on what, and why.' I actually like this, but it's a sidebar so we should put our heads together on how we want to sell it, if it comes to that.
2. We ditch it and find new data that doesn't have squirrelly dates in it. I don't love this, since there's a time cost associated with fishing out a new dataset and rejigging all our code and verbiage to work with it. We also lose the teachable moment. 
3. We make a pull request and get normDate folded into the glatos package. I lowkey think we should do something like this anyway, since it might conceivably be useful above and beyond this instance, but obviously it's a time bottleneck on when/if it gets merged and who knows when that'll be. 

Lemme know your thoughts. 

Also as with other lessons, this is going to need to be duplicated to work with the different datasets. I don't feel comfortable doing that since glatos isn't really my baby.

### CODE REVIEW

**Comment by CaitlinBate** [comment]
answering your direct Qs:

- i think all package names can be in backticks, including VTrack.
- re: NormDate, i think this is only applicable to the ACT-version of this lesson since it was the only one with the ugly dataset. i think we should just choose a new dataset to simplify the lesson, and have it match the smoothness of the other nodes. HOWEVER, we can add it to the `glatos` package that would be sweet for future-proofing this. but i think its out of the scope of the workshops

**Review by CaitlinBate — CHANGES_REQUESTED** [review]
line 14: function requires an "events" object to create a......

line 39 and 40 need to be swapped, the "kessel" line describes the rik_data object, while the "time interval method" describes the rit_data object.

line 54 needs to be attached to line 53.

line 56: we should have just cleaned the dataset/used a QC'd version of the dataset here...

line 106: "only keeps detections which occur on receivers for which we have deployment metadata. Detections with no deployment metadata are excluded"

**Review by CaitlinBate — CHANGES_REQUESTED** [review]
i still think we need to remove all the "clean the file" stuff from lines 55-78. instead, you should have a clean file to use for the workshop. whatever the result of the "normDate" function is should be the file provided to the attendees. the rest is out of the scope of this workshop.

todos:

- clean the file, test it
- put it into the correct folder in master (replaceing the one w bad dates)
- remove all the normDate stuff from the workshop
- maybe make a PR to add normDate to `glatos` just to keep it somewhere!

**Comment by jackVanish** [comment]
@CaitlinBate, maybe you can answer this better than I can: I've been checking this out for a while now and I _think_ the data may have already been cleaned up? Skipping the normDate part doesn't seem to cause any problems and running it, in fact, nukes most of the time column. Looking at the file it's drawing from, I don't see a discrepancy between the dates around the line that I magic-numbered into the code way back when. Also, at some point the file changed from an xls to an xlsx, fuelling my suspicion that somebody did something with it at some point (the code is still referencing the xls, which needs to be changed either way). Good catch that the code is a holdover from when we didn't have time to fix it, though. Can you spool through that part of the code and confirm that it's doing what it's supposed to be without any of the normDate stuff? It seems fine to me but I don't trust my knowledge 100% of the way on this one. Once we know for sure either way, I'll tidy up the data or code (as appropriate) and lesson.

**Review by CaitlinBate — COMMENTED** [review]
pulled the newest version of glatos package and:

line 65 arguments have changed: 

tags <- prepare_tag_sheet('Tag_Metadata/Proj58_Metadata_cownoseray.xlsx',sheet_name = 2, header_line = 5)

conversion to ATT no longer works - not sure whats going on. likely an issue because Im not using Ryan's fancy custom version

**Comment by CaitlinBate** [comment]
> @CaitlinBate, maybe you can answer this better than I can: I've been checking this out for a while now and I _think_ the data may have already been cleaned up? Skipping the normDate part doesn't seem to cause any problems and running it, in fact, nukes most of the time column. Looking at the file it's drawing from, I don't see a discrepancy between the dates around the line that I magic-numbered into the code way back when. Also, at some point the file changed from an xls to an xlsx, fuelling my suspicion that somebody did something with it at some point (the code is still referencing the xls, which needs to be changed either way). Good catch that the code is a holdover from when we didn't have time to fix it, though. Can you spool through that part of the code and confirm that it's doing what it's supposed to be without any of the normDate stuff? It seems fine to me but I don't trust my knowledge 100% of the way on this one. Once we know for sure either way, I'll tidy up the data or code (as appropriate) and lesson.

i agree, the file has been fixed already, so the NormDate stuff can go away

**Review by CaitlinBate — APPROVED** [review]

**Comment by jackVanish** [comment]
I made a new ticket to track issues with glatos against our code, so I'll merge this since it's just for text.

**Pull request merged**
